// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import TurboFormRedirectController from "./turbo_form_redirect_controller.js"
application.register("turbo-form-redirect", TurboFormRedirectController)

import FormController from "./form_controller.js"
application.register("form", FormController)

import ProfileFormController from "./profile_form_controller.js"
application.register("profile-form", ProfileFormController)

import WishlistFormController from "./wishlist_form_controller.js"
application.register("wishlist-form", WishlistFormController)
