AllCops:
  NewCops: enable
Style/Documentation:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Layout/LineLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Exclude:
    - "bin/bundle"
Metrics/PerceivedComplexity:
  Exclude:
    - "bin/bundle"
