services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  mailcatcher:
    image: dockage/mailcatcher:0.7.1
    ports:
      - 1080:1080
      - 1025:1025

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    stdin_open: true
    tty: true
    volumes:
      - .:/wishlise
    ports:
      - "3000:3000"
    depends_on:
      - db
